config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
# frozen_string_literal: true

class Home
  include Mongoid::Document
  include Mongoid::Enum

  before_validation :set_total_amount

  field :price, type: Float
  field :location, type: Array
  field :total_amount, type: Float
  field :extra_service, type: Float
  field :master_home_id, type: String
  field :home_features, type: Hash, default: { garden: false, furnished: false, gym: false }
  enum :status, [:in_progress, :published, :rented]

  has_many :rents
  belongs_to :owner

  validates :price, :extra_service, :total_amount, :home_features, :status, presence: true

  private

  def set_total_amount
    self.total_amount = price + extra_service
  end
end

app/models/owner.rb
# frozen_string_literal: true

class Owner
  include Mongoid::Document
  field :curp, type: String
  field :registered_in_srpago, type: Mongoid::Boolean

  has_many :homes
  belongs_to :user

  validates :curp, :registered_in_srpago, presence: true
end

app/models/rent.rb
# frozen_string_literal: true

class Rent
  include Mongoid::Document
  include Mongoid::Enum

  enum :status, %i[in_progress published rented]

  belongs_to :user
  belongs_to :home

  validates :status, presence: true
end

app/models/similar_home.rb
class SimilarHome
  include Mongoid::Document

  def self.owner_home
    owners_id = Owner.pluck(:id)
    homes = []

    owners_id.each do |id|
      owner = Owner.includes(:homes).find(id)
      homes = owner.homes
      next if homes.length == 1

      homes_size = homes.size
      homes.map do |home|
        #next if index + 1 < homes_size

        # if index + 1 < homes_size # guard clause

          current_home = Home.find_by(id: home)
          if current_home.master_home_id.nil? && current_home.published?
            # next_home = homes[index + 1]
            second_home = Home.find(homes)
            first_total_amount = current_home.total_amount
            second_total_amount = second_home.total_amount
            first_location = current_home.location
            second_location = second_home.location

            if first_total_amount == second_total_amount && first_location == second_location
              puts  "#{owner.user.name}, " \
                    "#{owner.user.email}, " \
                    "#{current_home.id}, " \
                    "#{current_home.total_amount}, " \
                    "#{current_home.status}, " \
                    "#{current_home.location}"
            end

          end

        # end

      end
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User
  include Mongoid::Document

  field :email, type: String
  field :name, type: String
  field :last_name, type: String
  field :mobile_phone, type: String
  field :work_place, type: String

  has_many :rents

  validates :name, :last_name, :mobile_phone, :work_place, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true

  after_create :send_mail

  private

  def send_mail
    UserMailer.new_user(self).deliver_now
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :name, :last_name, :mobile_phone, :work_place)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :mobile_phone %>
    <%= form.text_field :mobile_phone %>
  </div>

  <div class="field">
    <%= form.label :work_place %>
    <%= form.text_field :work_place %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Last name</th>
      <th>Mobile phone</th>
      <th>Work place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.mobile_phone %></td>
        <td><%= user.work_place %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Mobile phone:</strong>
  <%= @user.mobile_phone %>
</p>

<p>
  <strong>Work Place:</strong>
  <%= @user.work_place %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>